title: My personal blog - Avinash Erupaka
email: avinash.jvm10@gmail.com
description: This is where I share and discuss about software. The challenges, interesting problems I solve, findings, tips and tricks I learn in day-to-day life.
permalink: ':title/'
baseurl: ""
url: "https://avinasherupaka.github.io/techsavi.blog/"

# Author settings
author: Avinash Erupaka
author-pic: Avinash_4.jpg
about-author: My name is Avinash Erupaka. Iâ€™ve been passionately developing software for the past six years. I love speaking, traveling, and boxing. I enjoy building fast, responsive, intuitive, dynamic and robust web or mobile application for both small and enterprise scale. I have proficiency using tools like React.js, Redux, Bootstrap, Material Design for the front end. Node.js, Scala, Clojure and Java for the back end. I leverage AWS as a cloud provider and I am an AWS Certified Developer - Associate.

# Contact links
email: avinash.jvm10@gmail.com
website: https://avinasherupaka.github.io/
linkedin: https://www.linkedin.com/in/avinash-erupaka-956017154/
github: avinasherupaka # Add your Github handle

# Newsletter
mailchimp: 77335a05b8

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
